### ISSUE TITLE
ExcludeAppControlTypes Documentation Error

### ISSUE THREAD

**Issue by sirwes** [jguertl/SharePlugin#100]
This may or may not be an issue. In trying out the sample code in the documentation for the share options, I get the following error:

"Cannot implicitly convert type Plugin.Share.Abstractions.ShareUIActivityType[] to Plugin.Share.Abstractions.ShareAppControlType"

My code is 
            CrossShare.Current.Share(new ShareOptions
            {
                ChooserTitle = "Share Blog",
                ExcludedAppControlTypes = new [] { ShareUIActivityType.PostToFacebook}
            });

**Comment by jamesmontemagno** [comment]
Correct you would need to set : ExcludedUIActivityTypes  not ExcludedAppControlTypes

**Comment by sirwes** [comment]
Ah, I must have let it auto-enter too early. Thanks!
