### ISSUE TITLE
Xamarin.Android.Support.Compat version conflict with Xamarin Forms 3.2

### ISSUE THREAD

**Issue by DennisWelu** [jguertl/SharePlugin#102]
Attempting to update Xamarin.Forms to 3.2 results in a version conflict with this library around the Xamarin.Android.Support.Compat library:

> NU1107: Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 27.0.2 directly to project MyProject.Droid to resolve this issue. 
>  MyProject.Droid -> Xamarin.Forms 3.2.0.839982 -> Xamarin.Android.Support.v7.MediaRouter 27.0.2 -> Xamarin.Android.Support.v7.Palette 27.0.2 -> **Xamarin.Android.Support.Compat (= 27.0.2)** 
>  MyProject.Droid -> Plugin.Share 7.1.1 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> **Xamarin.Android.Support.Compat (= 25.4.0.2)**.

Looks like the required version of Xamarin.Android.Support.Compat with Xamarin Forms 3.2 is now 27.0.2.

**Comment by dannmat** [comment]
I also have this issue

**Comment by jamesmontemagno** [comment]
Install 27.0.2 first of Support.Compat and CustomTabs

I would recommend using Xamarin.Essentials now as that has all of these features included.

**Comment by DennisWelu** [comment]
I could not install Xamarin.Android.Support.Compat or CustomTabs immediately due to incompatibility with implied dependencies from XF3.1. NuGet install could be forced I'm sure, but what I did was uninstall the share plugin, then do the upgrade to XF3.2, then install Compat and CustomTabs.
