### ISSUE TITLE
Thumbnail images in iOS WeChat Share 

### ISSUE THREAD

**Issue by WongWeiLoon** [jguertl/SharePlugin#103]
We can share links to WeChat but we always get a oddly thumbnail images as shown below.

![2018-10-02_1845](https://user-images.githubusercontent.com/21115553/46344372-7d44ce00-c673-11e8-9a66-310bf7242eb6.png)

This issues occurred ONLY on iOS.
May I know how can I set the thumbnail images? or maybe hide this thumbnail image?
Thank you. :)

**Comment by jamesmontemagno** [comment]
No new functionality will be added to this library and all are moving to https://github.com/xamarin/Essentials
