### ISSUE TITLE
On iOS share sheet display nothing?

### ISSUE THREAD

**Issue by sumeyyaarar** [jguertl/SharePlugin#104]
<img width="406" alt="screen shot 2018-10-11 at 17 09 14" src="https://user-images.githubusercontent.com/12747384/46810024-748d7f80-cd78-11e8-9d98-16a9463551bf.png">

**Comment by jamesmontemagno** [comment]
What are you sharing? Can you show a code snippet?

I would also recommend moving to Xamarin.Essentials as it is the replacement for this library: https://docs.microsoft.com/en-us/xamarin/essentials/data-transfer
