### ISSUE TITLE
[URGENT] Implementing Facebook ShareDialog in this library

### ISSUE THREAD

**Issue by peppe130** [jguertl/SharePlugin#105]
Hi,

since 1 August 2018 Facebook officially deprecated **publish_actions** permission and replaced it with an in-app **ShareDialog**. Furthermore I can't implement this ShareDialog into my App because currently I'm using your **SharePlugin** library. Could you please update your code? It's fairly urgent. Thank you so much.

**Comment by jamesmontemagno** [comment]
Those are native dependencies of their libraries, I would just bring in their dependencies and create an interface for them. This library is now deprecated as Xamarin.Essentials is taking it's place.
