### ISSUE TITLE
Sharelink method is not coming while accessing

### ISSUE THREAD

**Issue by chinni-nag** [jguertl/SharePlugin#109]
Hi, @jguertl  Sharelink method is not coming while sharing a link to twitter . Please let me know how to do that.
Thanks.

**Comment by jamesmontemagno** [comment]
This library is officially deprecated, please use Xamarin.Essentials: https://github.com/jguertl/SharePlugin#library-is-deprecated

**Comment by chinni-nag** [comment]
@jamesmontemagno  While sharing a link to twitter it sharing as a text but need as a link , How to achieve it . Please let me know. Thanks.
