### ISSUE TITLE
Facebook share shows none of the text

### ISSUE THREAD

**Issue by seansparkman** [jguertl/SharePlugin#13]
Here is a snippet of the code.  I replaced a few things, but here it is.

> await CrossShare.Current.Share("I'm using (my new app) to get great seats to awesome shows, check it out! appStoreURL", "Hey, Check out (my new app)!");

**Comment by seansparkman** [comment]
I am not seeing any other apps where this actually works.

**Comment by jamesmontemagno** [comment]
This is on iOS?

**Comment by jamesmontemagno** [comment]
I tested on simulator and did a test on clipboard and that seemed to work... hmmmm https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.iOSUnified/ShareImplementation.cs#L42-L63

Looks pretty accurate and has worked in the past... Perhaps it should be:

https://developer.xamarin.com/api/type/MonoTouch.UIKit.UIActivityViewController/

```
  var item = UIActivity.FromObject (textField.Text);
    var activityItems = new NSObject[] { item };
    UIActivity[] applicationActivities = null;
    
    var activityController = new UIActivityViewController (activityItems, applicationActivities);
```

will test today and push package.

**Comment by jamesmontemagno** [comment]
It actually looks like Facebook broke it: http://stackoverflow.com/questions/29890747/ios-how-to-share-text-and-image-on-social-networks

I have added a way to remove specific UIActivityTypes, in the iOS project:

call... 
```
ShareImplementation.ExcludedUIActivityTypes = new List<string>{ UIActivityType.PostToFacebook};
```

Additionally, if you are calling only from iOS then you can use an overloaded constructor. Will be available in the next version.
