### ISSUE TITLE
Processor architecture mismatch on Windows 10 ARM

### ISSUE THREAD

**Issue by xtumiox** [jguertl/SharePlugin#17]
Hi, I installed the Plugin.Share via NuGet on my Windows 10 project but when I try to compile or deploy my app to the Phone I get this error:

"There was a mismatch between the processor architecture of the project being built "ARM" and the processor architecture of the reference "C:\Users\Matteo\.nuget\packages\Plugin.Share\3.2.1\lib\UAP10\Plugin.Share.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project."

Seems to compile fine when I'm on x86 (for example a test on the emulator), but my app is a Phone app, so this plugin should work on mobile with ARM processor too.

**Comment by jamesmontemagno** [comment]
Interesting... this may have to do with the CI server... let me investigate and push something new next week.

**Comment by jamesmontemagno** [comment]
@xtumiox Can you please try 3.2.2 and let me know as I don't have a device sitting around currently.

**Comment by xtumiox** [comment]
@jamesmontemagno unfortunately 3.2.2 has the same problem.

**Comment by jamesmontemagno** [comment]
Will be fixed in next version. Figured out what I did. should be version 3.3.X
