### ISSUE TITLE
Unable to share text on Windows 10

### ISSUE THREAD

**Issue by xtumiox** [jguertl/SharePlugin#18]
Hi,

Not sure this is an issue, but I just checked the latest version and I found that the Share function never fires the share on Windows 10. If I want to share simple text I should call:

`await CrossShare.Current.ShareLink("", "Text", "Title");`

Where the link is an empty string. Is this by design?

Also, when I try to share I never get both Title and Text property shown, only one at a time.

**Comment by jamesmontemagno** [comment]
Hmmm,

I will look into it today.

Please also be cognizant of your titles.

**Comment by jamesmontemagno** [comment]
You can try 3.3.5 and it should be fixed up.

This is the code that gets executed: https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.WindowsPhone81/ShareImplementation.cs#L56-L96

Via this documentation:
https://msdn.microsoft.com/en-us/library/windows/apps/mt243293.aspx
