### ISSUE TITLE
"Share with Facebook" iOS not pulling through text

### ISSUE THREAD

**Issue by johnhearfield** [jguertl/SharePlugin#19]
When having the Facebook app installed and setting it as a share application on iOS 9.2 (latest), the message text is not being pulled through. I have tried with Twitter and that seems to pull the text through fine, same with iMessage, but not the Facebook App.

![img_0559](https://cloud.githubusercontent.com/assets/12893912/12713778/88e21944-c8c8-11e5-87ff-d2b87ee3bc16.jpg)
![img_0560](https://cloud.githubusercontent.com/assets/12893912/12713779/88e33892-c8c8-11e5-9fe4-8ee863f273fe.jpg)

**Comment by jamesmontemagno** [comment]
Please see https://github.com/jguertl/SharePlugin/issues/13
