### ISSUE TITLE
Facebook blank

### ISSUE THREAD

**Issue by ianvink** [jguertl/SharePlugin#20]
Hi Guys. What a wonderful tool you have made. Thank you.

I have noticed on an iOS device, Xamarin.Forms when I choose "Facebook" as the sharing option, that the text is blank in the Facebook form that appears. Sharing to a Note or Message or Twitter works wonderfully though.

Is there some setting that needs to be made first?

**Comment by jamesmontemagno** [comment]
Please see: https://github.com/jguertl/SharePlugin/issues/13#issuecomment-177741073

Facebook does not support it anymore :( You should remove them from the share options
