### ISSUE TITLE
Android Cancel

### ISSUE THREAD

**Issue by ryanherman** [jguertl/SharePlugin#22]
When you hit back or anywhere not on the messaging, the app goes into the background.

**Comment by jamesmontemagno** [comment]
Can you describe and share the code you are using and your workflow. The plugin does a lot of things.

**Comment by ryanherman** [comment]
Ah, I figured out the issue and maybe make a note but somehow NoHistory = false snuck into my Activity page and therefore caused many many issues.  Such issues were, after Media was done selecting or taking a picture it would go back to main title page or if you used share and canceled out, it would leave the app.
