### ISSUE TITLE
Crash at UIKit.UIViewController:get_PopoverPresentationController on iOS 7

### ISSUE THREAD

**Issue by therealjohn** [jguertl/SharePlugin#23]
When trying to share on iOS 7, it will crash. I believe it's because of the following API call:

https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.iOSUnified/ShareImplementation.cs#L102

This is only available in iOS 8.

**Comment by jamesmontemagno** [comment]
@therealjohn can you PR me :)

**Comment by therealjohn** [comment]
Yes, I have been meaning to do this. Thanks for reminding me. Incoming soon.
