### ISSUE TITLE
Share title is not set as email subject when sharing to Mail app on iOS

### ISSUE THREAD

**Issue by dominik-weber** [jguertl/SharePlugin#27]
When sharing a link or text to the mail app on iOS the subject of the email is not filled in. The mail body works as expected.
From a quick google search I found this stackoverflow thread which could be used to solve this issue: http://stackoverflow.com/questions/17020288/how-to-set-mail-subject-in-uiactivityviewcontroller-and-also-twitter-sharing-te

**Comment by dominik-weber** [comment]
After some more testing I found a few similar bugs on android:

**Share with Gmail app**
- Share(): Email body = message, email subject not set; title is ignored
- ShareLink(): Email body = link, email subject = message; title is ignored

**Share with Hangouts/SMS app**
- Share(): hangouts message = message; title is ignored
- ShareLink(): hangouts message = link; title+message ignored

This is a very promising project, I'm looking forward to integrating it into our app. Hope these issues will be adressed however ;)

**Comment by jamesmontemagno** [comment]
The app uses standard apis to send them out, it is up to the app that responds. I will poke around a bit, but having the Title ignored makes a lot of sense in the scenarios you are showing.

Share Link always give priority to the link.

**Comment by DavePilks** [comment]
@jamesmontemagno so just to be clear, there is no way to set the subject of an email via this plugin? Barring sending a link.

**Comment by jamesmontemagno** [comment]
I will take a look at the behavior of it, but it is a generic share sheet on each platform. Essentially most of the time you are just sharing the core message.

So in each example for email the body is being set as the most important on android. The title is what comes up on the share sheet. Not what is actually passed to the intent.  See: https://developer.android.com/training/sharing/send.html you can only pass 1 thing.

Each app can consume it differently, same is true for iOS too. I will look to see why the email app in iOS isn't putting the message in the subject though as that seems odd or just how it consumes it.

If you are looking specifically to send emails from your app then use the messaging plugin: https://github.com/cjlotz/Xamarin.Plugins/tree/master/Messaging

**Comment by dominik-weber** [comment]
@jamesmontemagno do you accept pull requests on this issue?

**Comment by jamesmontemagno** [comment]
Absolutely do :)

Just write up the fix, reasons, and the changes in behavior.

**Comment by dominik-weber** [comment]
Finally I found some time to make the necessary changes.

With the fix the title is now applied to email subject when sharing with mail apps on Android and iOS. tested with the default mail app on iOS and Gmail on Android. Also the message and link are shared consistently across platforms: <message>\n<link>

One small problem still exists: When sharing a link with a message on android and selecting copy to clipboard on the share popup both the message and the link are copied, so you cannot directly paste into a browser. I believe there is no good workaround for this, as you already mentioned you can only share one piece of content on Android. Also we might consider allowing the user to specify different values for subject and popup title on supported platforms in the future.
