### ISSUE TITLE
Always falls back to launching default browser.

### ISSUE THREAD

**Issue by oaestella** [jguertl/SharePlugin#28]
Am I just missing something? I have Chrome Browsers installed in my phone. But it just keeps launching the browser as it is.

How do I simulate the transition shown with Chrome Custom Tabs?

**Comment by jamesmontemagno** [comment]
As long as you didn't remove the current activity plugin at all it should attempt to. I would read through the logs:

https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.Android/ShareImplementation.cs#L37  is where it does the check.

**Comment by jamesmontemagno** [comment]
Can't reproduce any issue here.
