### ISSUE TITLE
FR: Share picture

### ISSUE THREAD

**Issue by thomashagstrom** [jguertl/SharePlugin#29]
Any particular reason you can't share a picture? That feels like the most common thing to share.

**Comment by shrknt35** [comment]
If we could have a mechanism to share a files/document/picture that would be great.

**Comment by PetrVobornik** [comment]
Can you add support for sharing images, please? Sharing by image file path or by stream will be perfect. 
You just need a little to expand the existing code...
 
_Code for Android_ 
```csharp
public void ShareImage(string title, string text, string imagePath)
{
    var uri = (Android.Net.Uri.FromFile(new Java.IO.File(imagePath)));
    var sharingIntent = new Intent(Intent.ActionSend);  
    sharingIntent.SetType("image/png");
    sharingIntent.SetFlags(ActivityFlags.GrantReadUriPermission);
    sharingIntent.PutExtra(Intent.ExtraText, text);
    sharingIntent.PutExtra(Intent.ExtraStream, uri);
    var chooserIntent = Intent.CreateChooser(sharingIntent, title);
    chooserIntent.SetFlags(ActivityFlags.NewTask);
    Android.App.Application.Context.StartActivity(chooserIntent);
}
```
 
_Code for UWP_
```csharp
List<IStorageItem> imageItems = new List<IStorageItem>();
imageItems.Add(file);
request.Data.SetStorageItems(imageItems);
RandomAccessStreamReference imageStreamRef = RandomAccessStreamReference.CreateFromFile(file);
request.Data.Properties.Thumbnail = imageStreamRef;
request.Data.SetBitmap(imageStreamRef);
```

**Comment by prashantvc** [comment]
@PetrVobornik  could you send that code as PRs :)

**Comment by EmilAlipiev** [comment]
So is it merged in any Version?  Can we share already?  I cant see any Documentation about sharing image

**Comment by CarLoOSX** [comment]
Any update on this ?? I'm trying to get this option : SAVE IN FILES
![img_1270](https://user-images.githubusercontent.com/9008334/36587552-cdb9b356-1885-11e8-91ad-764e1fa27d9f.png)

**Comment by jitendrajadav** [comment]
Still waiting share a picture can you please update this is most common use please do it.

**Comment by EmilAlipiev** [comment]
Isnt this repo doing basically the same job but it is extended with pdf and image also? 
https://github.com/adamped/ShareDialog/tree/master/ShareDialog

According to this, it doesnt seem to be that hard to implement it.

**Comment by vd3d** [comment]
Any news ?

**Comment by jamesmontemagno** [comment]
No new functionality will be added to this library and all are moving to https://github.com/xamarin/Essentials
