### ISSUE TITLE
link sharing broken on iOS 9.1

### ISSUE THREAD

**Issue by kitkat14** [jguertl/SharePlugin#30]
Url is not shared on iOS. on Android works perfect. iOS changed rules ?
Tested on iOS 9.1

**Comment by jamesmontemagno** [comment]
What are you sharing it to? this will help in testing.

**Comment by kitkat14** [comment]
Shared to whatsapp, notes,mail.... all the same

**Comment by kitkat14** [comment]
Could you duplicate the bug ?

**Comment by jamesmontemagno** [comment]
Can you check 4.1.0-beta to see if it is fixed for you.

**Comment by kitkat14** [comment]
This will sound like a stupid question but how exactly do I do that ? I mostly used NuGet update.

**Comment by jamesmontemagno** [comment]
Inside of NuGet when you are on the update screen in VS you can check the "pre-release" button and it will show it.

If you are in Xamarin Studio, go in as if you are adding a new nuget and then check the "pre-release" check box and make sure to update all projects.

**Comment by kitkat14** [comment]
I updated the git but it still has the same issue. Android works perfect but on iOS 9.1 sharing links is not sharing the link. It shares the title and message but no link

**Comment by jamesmontemagno** [comment]
Interesting, can you paste you code snippet that you are calling so I can test it out.

**Comment by kitkat14** [comment]
This is in a button action

string position = item.latitude.ToString(CultureInfo.InvariantCulture) + "," + item.longitude.ToString(CultureInfo.InvariantCulture);
string label = AppResources.AppResources.itemShareText+ " " +item.exp_date.ToLocalTime();
string url = String.Format("http://maps.google.com/maps?q=loc:{0}({1})", position, label);
await CrossShare.Current.ShareLink(url, label, AppResources.AppResources.SharedOn + AppResources.AppResources.AppName);

**Comment by jamesmontemagno** [comment]
awesome thanks! will give it a spin next week when I am back from holiday.

**Comment by khadeeja-alif** [comment]
Url Sharing still doesn't work on iOS.
