### ISSUE TITLE
Xamarin.Forms Error When Called From Modal

### ISSUE THREAD

**Issue by 2ndCharter** [jguertl/SharePlugin#35]
I have run into an error when attempting to use the plugin from a ContentPage which was spawned from Navigation.PushModalAsync. The share option is being called by user interaction (clicking a share button) after the modal page loads. The error is:

`Warning: Attempt to present <UIActivityViewController: 0x7adde600> on <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x7cefb460> whose view is not in the window hierarchy!`

**Comment by Chico741** [comment]
Same issue here with a model view controller on iOS:

`Warning: Attempt to present <UIActivityViewController: 0x7feb5c7d3760> on <View: 0x7feb5c5785b0> whose view is not in the window hierarchy!`

**Comment by Chico741** [comment]
are there any new for this issue?

**Comment by jamesmontemagno** [comment]
What method are you attempting to use? Share?

**Comment by jamesmontemagno** [comment]
I am releasing a 5.0 beta to try. I put in a test for pushing from modal and it seem good here. Try that one or create a small repo for me

**Comment by Rostegk** [comment]
The problem is within the GetVisibleViewController() method. In some cases when there are multiple ViewControllers on the stack, the TopViewController ist not the one being currently displayed. 
I changed it for VisibleViewController and it's working perfectly in our case.

This is how the Method works for us:

    UIViewController GetVisibleViewController()
    {
            var rootController = UIApplication.SharedApplication.KeyWindow.RootViewController;

            if (rootController.PresentedViewController == null)
                return rootController;

            if (rootController.PresentedViewController is UINavigationController)
            {
                return ((UINavigationController)rootController.PresentedViewController).VisibleViewController;
            }

            if (rootController.PresentedViewController is UITabBarController)
            {
                return ((UITabBarController)rootController.PresentedViewController).SelectedViewController;
            }

            return rootController.PresentedViewController;
    }

If this is a valid solution, do you create a new package for nuget in the near future? Would be cleaner than using the custom build package.

**Comment by jamesmontemagno** [comment]
That is literally the same code as: https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.iOSUnified/ShareImplementation.cs#L229-L247

What version of the plugin are you using?

**Comment by Rostegk** [comment]
No it is not, in Line 238, i changed the TopViewController to VisibleViewController.

We tried to use the latest Version of the plugin but got the error with the window hierarchy, so i checked out the current code, and fixed the problem by changing TopViewController to VisibleViewController.

**Comment by jamesmontemagno** [comment]
Gotcha, let me see, that was hard to see, please just send a PR down next time.

**Comment by Rostegk** [comment]
I will next time and thanks for looking into it.

**Comment by jamesmontemagno** [comment]
:) pushed out a new beta package. Will probably push to production next week

**Comment by NinjaFocks** [comment]
Did this get pushed out? Still having this problem on 5.0.0.3-beta which we updated to today.

**Comment by jamesmontemagno** [comment]
Yes, this has the verified fix in 5.0.0.3-beta and was working great for me. If you have a new repo then let me kno

**Comment by NinjaFocks** [comment]
Created an issue & PR 27 days ago.
