### ISSUE TITLE
Sharing Empty - iOS 10.1

### ISSUE THREAD

**Issue by kikolopes90** [jguertl/SharePlugin#36]
## Bug

Version Number of Plugin: 5.0.0.2-beta
Device Tested On: iPhone5 iOS 10.1

Android works fine. IOS sharing is empty, does not appear "Facebook" or "Messenger" or the others.

https://cloud.githubusercontent.com/assets/21179985/20539428/db7c3f7e-b0ec-11e6-9b68-13cc1871ac85.PNG

### Steps to reproduce the Behavior

```
var sharemessage = new ShareMessage
{
     Title = WTranslate.SendTo,
     Url = $"maps.google.com/maps?q={lat},{lon}"
};

await CrossShare.Current.Share(sharemessage);
```

**Comment by jamesmontemagno** [comment]
I am pretty sure that Facebook does not actually support share anymore via share sheet, which is unfortunate. Recommendation is to filter out share to Facebook. 

See: https://github.com/jguertl/SharePlugin/issues/13#issuecomment-177741073

**Comment by kikolopes90** [comment]
Version Number of Plugin: 4.0.3
Device Tested On: iPhone5 iOS 10.1

I tested this version, it's working. The beta does not, nothing appears.

https://cloud.githubusercontent.com/assets/21179985/20562046/958e26c0-b179-11e6-9a9c-adfb6a83fcdf.PNG

**Comment by jamesmontemagno** [comment]
Test out 5.0.0.3-beta I tested on device and works great.

Be aware that I have now removed all obsolete methods so you may need to update code.

**Comment by kikolopes90** [comment]
It works already, thank you :)

```
await CrossShare.Current.Share(new ShareMessage
{
     Text = $"maps.google.com/maps?q={lat},{lon}"
},
new ShareOptions
{
     ExcludedUIActivityTypes = new []{ ShareUIActivityType.PostToFacebook }
});
```

**Comment by jamesmontemagno** [comment]
By default facebook will be discluded :)
