### ISSUE TITLE
Can it be used inside Xamarin Extensions?

### ISSUE THREAD

**Issue by carlosagsmendes** [jguertl/SharePlugin#39]
Hi there, 

Do you know if we can use this plugin inside an iOS Share Extension?

I'm asking because I saw that there are some limitations to [Extensions](https://developer.xamarin.com/guides/ios/platform_features/introduction_to_extensions/#Limitations)

Basically, I want to create a share button that will open a WebForm, passing the current URL, and allowing the user to answer a few questions about what he is sharing.

Thanks in advance

**Comment by jamesmontemagno** [comment]
Most likely not as it uses some of those APIs, but I have never tried.
