### ISSUE TITLE
IOS references are not ok

### ISSUE THREAD

**Issue by saramgsilva** [jguertl/SharePlugin#4]
In documentation you have

> In your iOS, Android and Windows Phone projects call:
Xamarin.Forms.Init();
ShareImplementation.Init();

but in IOS the nuget one install one dll, the Share.Forms.Plugin.Abstractions.

**Comment by saramgsilva** [comment]
Looks like you will not update it :( this project looks very nice....

**Comment by jguertl** [comment]
Hey @saramgsilva!
Please feel free to create a pull requests with the necessary changes.

**Comment by jamesmontemagno** [comment]
Fixing in next version

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Share.Plugin.Xamarin.Forms/2.0.0-alpha1
