### ISSUE TITLE
Linker Issue

### ISSUE THREAD

**Issue by codehippie1** [jguertl/SharePlugin#41]
I have chosen Android Options -> Linker -> Sdk Assemblies only in my Xamarin.Android project settings.

Getting the below error with Plugin.Share 5.0.0.0 (Also tried latest beta; same result)

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Reference to metadata item 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null') from 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    --- End of inner exception stack trace ---
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1586,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jguertl/SharePlugin/issues/40 See the resolve here

**Comment by jamesmontemagno** [comment]
Try: 5.1.0.14-beta

**Comment by jamesmontemagno** [comment]
6.1.0.19-beta is built against 25.1.1 and validated working in the test sample app on 25-1-1-support branch. 5.x will remain on 23.x support libraries

**Comment by codehippie1** [comment]
Thanks James.

I have went ahead and downloaded the source code to compile it against the Frameworks that are compatible. Then referenced them individually in my PCL and Android projects; and solved my problem.

Which beta I should be testing against 5.1 or 6.1. I could test and let you know the results.

**Comment by codehippie1** [comment]
Hi James,

I have tested against 6.1.0.19-beta, and unfortunately this issue still persists. The app crashes at runtime, and producing the below error.

`04-24 12:48:15.328 I/MonoDroid( 4059): UNHANDLED EXCEPTION:
04-24 12:48:15.358 I/MonoDroid( 4059): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
04-24 12:48:15.358 I/MonoDroid( 4059):   at SampleApp.Util+<OpenBrowser>d__0.MoveNext () [0x0000f] in D:\Playground\Xamarin\SampleApp\SampleApp\SampleApp\Util.cs:14 
04-24 12:48:15.358 I/MonoDroid( 4059): --- End of stack trace from previous location where exception was thrown ---
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
04-24 12:48:15.358 I/MonoDroid( 4059):   at SampleApp.Droid.RepoAdapter+<>c__DisplayClass11_0+<<GetView>b__0>d.MoveNext () [0x0002a] in D:\Playground\Xamarin\SampleApp\SampleApp\SampleApp.Android\RepoAdapter.cs:69 
04-24 12:48:15.358 I/MonoDroid( 4059): --- End of stack trace from previous location where exception was thrown ---
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-24 12:48:15.358 I/MonoDroid( 4059):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
04-24 12:48:15.358 I/MonoDroid( 4059):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
04-24 12:48:15.358 I/MonoDroid( 4059):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
04-24 12:48:15.358 I/MonoDroid( 4059):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Java.Lang.IRunnable.cs:81 
04-24 12:48:15.358 I/MonoDroid( 4059):   at (wrapper dynamic-method) System.Object:62463758-4aa4-4268-b417-6d8efb298567 (intptr,intptr)
04-24 12:48:15.388 W/art     ( 4059): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
04-24 12:48:15.398 D/Mono    ( 4059): DllImport searching in: '__Internal' ('(null)').
04-24 12:48:15.398 D/Mono    ( 4059): Searching for 'java_interop_jnienv_throw'.
04-24 12:48:15.408 D/Mono    ( 4059): Probing 'java_interop_jnienv_throw'.
04-24 12:48:15.408 D/Mono    ( 4059): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

04-24 12:48:26.488 D/Mono    ( 4059): [0x960ff930] worker finishing
Thread finished: <Thread Pool> #8
The thread 'Unknown' (0x8) has exited with code 0 (0x0).
04-24 12:48:29.148 E/mono    ( 4059): 
04-24 12:48:29.148 E/mono    ( 4059): Unhandled Exception:
04-24 12:48:29.148 E/mono    ( 4059): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
04-24 12:48:29.148 E/mono-rt ( 4059): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.`

Here is the packages.config for android project
`  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid71" />
  <package id="Plugin.Share" version="6.1.0.19-beta" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.Connectivity" version="2.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.1.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.1.1" targetFramework="monoandroid71" />`
