### ISSUE TITLE
Error building Android project in Release mode

### ISSUE THREAD

**Issue by plneto** [jguertl/SharePlugin#43]
I'm getting the following error when building my Android project in Release mode with the link behaviour as _Link SDK assemblies_ only. It works fine when I select _Don't Link_. 

This problem started happening after I updated the android packages to 25.1.1

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets (_LinkAssembliesShrink target) ->
> 			/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in assembly 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded.

**Comment by jamesmontemagno** [comment]
Revert the custom tabs package back to what it was built against .See #40

**Comment by jamesmontemagno** [comment]
Try: 5.1.0.14-beta

**Comment by plneto** [comment]
Thanks for the update but I'm still getting the same error when using 5.1.0.14-beta and Android 25.1.1

**Comment by jamesmontemagno** [comment]
I removed it because someone said it didn't work either

**Comment by jamesmontemagno** [comment]
6.1.0.19-beta is built against 25.1.1 and validated working in the test sample app on 25-1-1-support branch. 5.x will remain on 23.x support libraries

**Comment by plneto** [comment]
It's working with 6.1.0.19-beta. Thanks James 👍
