### ISSUE TITLE
Android problem

### ISSUE THREAD

**Issue by carvalla** [jguertl/SharePlugin#46]
When I try to share a text that is too long (more than 1500 lines), in android does not show the options to share, but in iOS no problem, I have managed to share 20200 lines of text.

Thanks for the help

**Comment by jamesmontemagno** [comment]
My assumption is that you hit a limit in Android, do you have the output?

**Comment by carvalla** [comment]
Hi, thanks for your response,
I'm not have the output!
Effectively there is a limit in Android of 1MB, so I could not use the plugin. 
do you know if the plugin supports a text file with .txt extension?
Thank you!

**Comment by jamesmontemagno** [comment]
We do not currently do sharing of documents, but it is on the list to implement and a feature is already created
