### ISSUE TITLE
Can't use ShareImplementation.Init()

### ISSUE THREAD

**Issue by jbravobr** [jguertl/SharePlugin#5]
Hi!

Any clues why I can't instantiate de plugin in the platform specific with the instruction ShareImplementation.Init() ?

**Comment by jamesmontemagno** [comment]
Will be fixed with V2 with new unified support. Will have a new preview package soon.

**Comment by jamesmontemagno** [comment]
Checkout v2: https://www.nuget.org/packages/Share.Plugin.Xamarin.Forms/2.0.0-alpha1
