### ISSUE TITLE
5.0 doesnt work for sharing url

### ISSUE THREAD

**Issue by EmilAlipiev** [jguertl/SharePlugin#52]
Previously i was doing with 4.03. works just fine 
```

  public Command ShareCommand
        {
            get
            {
                return new Command(async () =>
                {
                    await Plugin.Share.CrossShare.Current.ShareLink(url:
					"https://someurl", title: "myapp",
                      message: "test test");
                });
            }
        }

```
I just upgraded to 5.0 and adjusted my code as below
```

  public Command ShareCommand
        {
            get
            {
                return new Command(async () =>
                {
                    try
                    {
                        await Plugin.Share.CrossShare.Current.Share(new Plugin.Share.Abstractions.ShareMessage
                        {
                            Url = "https://someurl",
                            Title = "myapp",
                            Text = AppRes.ShareMessage
                        }, new Plugin.Share.Abstractions.ShareOptions { ChooserTitle = "test Title" });
                    }
                    catch (Exception ex)
                    {
                    
                    }
                   
                });
            }
        }
```

but it throws exception for me. am I doing something wrong?

**Comment by jamesmontemagno** [comment]
What is the exception?

**Comment by EmilAlipiev** [comment]
Sorry for not providing exception details. I was just in rush and I thought about creating issue after reverted my changes back. exception was something like "Cannot create request with id xxxx" for Android.Support.V4 , I recognized that it updated also my Android.Support.V4 library (probably related to Customtabs). I tried again just now and everything went smooth, I tested on android emulator and also on uwp, it worked fine but I would keep the issue until I test on real device later in the evening. because exception was for a specific device which I dont have it with me right now. I let you know later. thanks.

**Comment by jamesmontemagno** [comment]
You probably need the latest beta perhaps if you are using the newer 25.x support libraries...

**Comment by EmilAlipiev** [comment]
@jamesmontemagno   Exception persists on the device although it works on emulator. I tested on 2 physical devices. Sony xperia z3 and samsung s5 both crashes with the exception below. I am using 23.3 support libraries

05-09 17:56:29.996 I/MonoDroid( 1844): System.TypeLoadException: Could not resolve type with token 01000129
05-09 17:56:29.996 I/MonoDroid( 1844):   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00031] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84 
05-09 17:56:29.996 I/MonoDroid( 1844):   at myApp.DashboardPageModel+<>c.<get_ShareCommand>b__1_0 () [0x00013] in <b3fd3706369d47d4b6eab5a9766772e6>:0 
05-09 17:56:29.996 I/MonoDroid( 1844):   at Xamarin.Forms.Command+<>c__DisplayClass3_0.<.ctor>b__0 (System.Object o) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Command.cs:73 
05-09 17:56:29.996 I/MonoDroid( 1844):   at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Command.cs:107 
05-09 17:56:29.996 I/MonoDroid( 1844):   at Xamarin.Forms.MenuItem.Xamarin.Forms.IMenuItemController.Activate () [0x00010] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\MenuItem.cs:93 
05-09 17:56:29.996 I/MonoDroid( 1844):   at Xamarin.Forms.Platform.Android.GenericMenuClickListener.OnMenuItemClick (Android.Views.IMenuItem item) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\GenericMenuClickListener.cs:18 
05-09 17:56:29.996 I/MonoDroid( 1844):   at Android.Views.IMenuItemOnMenuItemClickListenerInvoker.n_OnMenuItemClick_Landroid_view_MenuItem_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_item) [0x00011] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Views.IMenuItem.cs:295 
05-09 17:56:29.996 I/MonoDroid( 1844):   at (wrapper dynamic-method) System.Object:1c25e1cb-1094-4a7c-a33c-cac5eae78d88 (intptr,intptr,intptr)
05-09 17:56:30.036 W/Xamarin.Insights( 1844): Warning: Unhandled exception: System.TypeLoadException: Could not resolve type with token 01000129
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00031] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at myApp.DashboardPageModel+<>c.<get_ShareCommand>b__1_0 () [0x00013] in <b3fd3706369d47d4b6eab5a9766772e6>:0 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at Xamarin.Forms.Command+<>c__DisplayClass3_0.<.ctor>b__0 (System.Object o) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Command.cs:73 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Command.cs:107 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at Xamarin.Forms.MenuItem.Xamarin.Forms.IMenuItemController.Activate () [0x00010] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\MenuItem.cs:93 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at Xamarin.Forms.Platform.Android.GenericMenuClickListener.OnMenuItemClick (Android.Views.IMenuItem item) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\GenericMenuClickListener.cs:18 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at Android.Views.IMenuItemOnMenuItemClickListenerInvoker.n_OnMenuItemClick_Landroid_view_MenuItem_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_item) [0x00011] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Views.IMenuItem.cs:295 
05-09 17:56:30.036 W/Xamarin.Insights( 1844):   at (wrapper dynamic-method) System.Object:1c25e1cb-1094-4a7c-a33c-cac5eae78d88 (intptr,intptr,intptr)
05-09 17:56:30.296 D/Mono    ( 1844): DllImport searching in: '__Internal' ('(null)').
05-09 17:56:30.296 D/Mono    ( 1844): Searching for 'java_interop_jnienv_get_long_field'.
05-09 17:56:30.296 D/Mono    ( 1844): Probing 'java_interop_jnienv_get_long_field'.
05-09 17:56:30.296 D/Mono    ( 1844): Found as 'java_interop_jnienv_get_long_field'.
05-09 17:56:30.366 D/Mono    ( 1844): DllImport searching in: '__Internal' ('(null)').
05-09 17:56:30.366 D/Mono    ( 1844): Searching for 'java_interop_jnienv_set_int_field'.
05-09 17:56:30.366 D/Mono    ( 1844): Probing 'java_interop_jnienv_set_int_field'.
05-09 17:56:30.366 D/Mono    ( 1844): Found as 'java_interop_jnienv_set_int_field'.
05-09 17:56:30.376 D/Mono    ( 1844): DllImport searching in: '__Internal' ('(null)').
05-09 17:56:30.376 D/Mono    ( 1844): Searching for 'java_interop_jnienv_call_long_method_a'.
05-09 17:56:30.376 D/Mono    ( 1844): Probing 'java_interop_jnienv_call_long_method_a'.
05-09 17:56:30.376 D/Mono    ( 1844): Found as 'java_interop_jnienv_call_long_method_a'.
05-09 17:56:30.446 D/Mono    ( 1844): Assembly Ref addref HockeySDK.AndroidBindings[0xa9810620] -> System[0x95f0d720]: 15
05-09 17:56:30.456 W/art     ( 1844): JNI RegisterNativeMethods: attempt to register 0 native methods for android.r

**Comment by jamesmontemagno** [comment]
Hard to say, can you create a small repo for me?

**Comment by jamesmontemagno** [comment]
Working great in 7.0

**Comment by EmilAlipiev** [comment]
Hi James, Quick question Does 7.0 require suppor libraries version 25 and above? Because Xamarin Forms has a [bug ](https://bugzilla.xamarin.com/show_bug.cgi?id=53179)currently  and prevent me and many people to upgrade suppor libraries :(

**Comment by jamesmontemagno** [comment]
yes, 25.3.1 are required for 7.0

**Comment by EmilAlipiev** [comment]
Ok, until this bug is fixed by xamarin. I would like to keep 4.03 version as it works fine on android and ios for me. but I am having problem with UWP for this version. It throws exception as below. Is that something you can  have a guess what could be the problem.

```

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Plugin.Share.Abstractions.IShare.ShareLink(System.String, System.String, System.String)'.
   at myWorkout.PageModel.<>c.<<get_ShareCommand>b__1_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at myWorkout.PageModel.<>c.<get_ShareCommand>b__1_0()
   at Xamarin.Forms.Command.<>c__DisplayClass3_0.<.ctor>b__0(Object o)
   at Xamarin
```

**Comment by chinni-nag** [comment]
@EmilAlipiev  Can you Please confirm me that can i share a link to social media using this plugin. Thanks .

**Comment by jamesmontemagno** [comment]
This library is officially deprecated, please use Xamarin.Essentials: https://github.com/jguertl/SharePlugin#library-is-deprecated
