### ISSUE TITLE
Wrong popover arrow direction on iPad using Forms

### ISSUE THREAD

**Issue by smarongiu** [jguertl/SharePlugin#54]
Using Xamarin Forms with Share Plugin, the popover view is always archored to the top-left of the root view.

**Comment by adamzucchi** [comment]
Bump

**Comment by jamesmontemagno** [comment]
It is already fixed in a PR, but haven't tested it and I am not sure about the code to be honest, but you could test.

**Comment by Sebastian1989101** [comment]
Is it possible to push a alpha or beta release to NuGet with the changes from the PR? I tested the PR in one project and it seems to work fine there and it would be much cleaner just to update the NuGet package in the other projects for me.
