### ISSUE TITLE
Status Bar color control

### ISSUE THREAD

**Issue by jphenow** [jguertl/SharePlugin#56]
Our status bar text is white on our app - is there a preferred way to set it to black for the duration of open-browser?

![image 2017-05-31 at 3 34 09 pm](https://cloud.githubusercontent.com/assets/319230/26652781/9dfc616e-4616-11e7-9d34-d8c987245722.png)

**Comment by jphenow** [comment]
I was able to solve this by altering status bar text color before openning browser then ensuring I set it to our default on view-will-appear:

```
UIApplication.SharedApplication.SetStatusBarStyle(UIStatusBarStyle.Default, true);
```

**Comment by jamesmontemagno** [comment]
:) I should probably add it to the API though... Will re-open so you shouldn't have to do this.

**Comment by jphenow** [comment]
:) That'd be great!

**Comment by jamesmontemagno** [comment]
Did you have to do anything to revert it back?

**Comment by jphenow** [comment]
Yea on the calling page we actually added a renderer that reverts it in in the ViewWillAppear - specifically did it there because OnAppearing is sort of late in the lifecycle (and it's noticeable)

**Comment by jamesmontemagno** [comment]
No new functionality will be added to this library and all are moving to https://github.com/xamarin/Essentials

**Comment by jphenow** [comment]
Lol. Little did I know when I wrote this that we’d technically be coworkers a year later 😂 👋
