### ISSUE TITLE
Android - functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by vectorlit** [jguertl/SharePlugin#57]
I am using the following code:

````
    CrossShare.Current.OpenBrowser(URL, new Plugin.Share.Abstractions.BrowserOptions
        {
            ChromeShowTitle = true,
            UseSafariReaderMode = true,
            UseSafariWebViewController = true
        });
````

It throws the following error:
````
Unhandled Exception:

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
````

I'm not sure what's happening. I just upgraded from an earlier version of the SharePlugin and it's now having this issue. I believe I do have the plugin installed properly:

![image](https://cloud.githubusercontent.com/assets/8009327/26737733/a22c13a6-4788-11e7-8a59-32e630c80b52.png)

(This also happens on version 5 and is not limited to the prerelease version)

**Comment by jamesmontemagno** [comment]
Do a clean and re-build perhaps just cached build stuff or uninstall and re-install.

**Comment by vectorlit** [comment]
As a follow-up, I was unable to get the nuget packages working, even after the following steps:
1) cleaning all projects
2) uninstalling packages
3) removing references
4) clearing nuget cache in VS
5) cleaning again
6) closing VS and restarting computer entirely (absurd, I know)
7) coming back into project, re-adding latest pre-release from nuget and retrying.
8) same result as initial post (builds fine, but error when actually hitting that piece of code).

In the end I followed all steps 1-6 again and built SharePlugin from source instead, manually added references. This worked. I do not have a solution for nuget if someone else experiences this same problem.

**Comment by jamesmontemagno** [comment]
Do you have advanced linker settings on? If so you may need to link skip the dlls.

**Comment by jamesmontemagno** [comment]
If you have a small repro project send it my way

**Comment by abozanona** [comment]
Same problem here. Uninstalling the plugin and installing v4.0.0 solved the problem.

The code will change to be something like `await CrossShare.Current.ShareLink(url, message, title);`
