### ISSUE TITLE
Always lists Facebook, Twitter, SinaWeibo, TencentWeibo regardless of what apps are actually installed.

### ISSUE THREAD

**Issue by trevoriancox** [jguertl/SharePlugin#6]
It's currently using Xamarin's enum for the menu of apps to share with, regardless of installed apps. (Social.SLServiceKind Enumeration)

Can we redo this, like a Cordova/Phonegap social plugin, using the built-in iOS Share dialog that lists the actual available apps?

Here's some sample code copied from that: 

```
UIActivityViewController *activityVC =
    [[UIActivityViewController alloc] initWithActivityItems:activityItems
                                      applicationActivities:applicationActivities];
    
    activityVC.excludedActivityTypes=@[UIActivityTypeAssignToContact, UIActivityTypeSaveToCameraRoll];
    
    [self.viewController presentViewController:activityVC animated:YES completion:nil];
```

**Comment by jamesmontemagno** [comment]
Please take a look at the v2 branch and let me know as I have moved some things around there.
