### ISSUE TITLE
iOS Not working

### ISSUE THREAD

**Issue by shabirjan** [jguertl/SharePlugin#60]
The Shareplugin doesn work on iOS, this is how i am calling 👍 

> var title = "KG - Daily tip";
>                         var message = response.Data.Text;
>                         await CrossShare.Current.Share(new ShareMessage()
>                         {
>                             Title = title,
>                             Text = message
>                         });

The app is in Xamarin Forms.

It works on Android but not on iOS, BTW the target is iOS 10.

**Comment by jamesmontemagno** [comment]
Unable to repro this on iOS at all.

Can you supply more code as to how this is being called?

**Comment by shabirjan** [comment]
Yes please check this link : https://gist.github.com/shabirjan/c8985850ed3e41cb137465bf07ff5b02#file-sharepluging-issue-ios

FYI i am using Prism Navigation and MVVM

**Comment by jamesmontemagno** [comment]
It could be because it comes after an alert dialog, some things changed to find the root, let me check.

**Comment by shabirjan** [comment]
Thanks BTW for now if i place this  `await Task.Delay(100);` before calling `CrossShare.Current.Share` it works

**Comment by jamesmontemagno** [comment]
I think i know what the issue is, i'll do a new pre-and let you know

**Comment by shabirjan** [comment]
Ok thanks :)

**Comment by shabirjan** [comment]
james Is it possible to know whether the sharing was successful or not? like we do in native a delegate is called when popup is dismissed can we somehow achieve in this plugin?

**Comment by jamesmontemagno** [comment]
There is not.
