### ISSUE TITLE
UIActivity Flipped in RTL

### ISSUE THREAD

**Issue by shabirjan** [jguertl/SharePlugin#64]
I am adding RTL functionality in my Xamarin Forms app and i am using this `UIApplication.SharedApplication.KeyWindow.Transform = CGAffineTransform.MakeScale(-1.0f, 1.0f);` 
to implement that in iOS, now it works fine, but when i click on share and the UIActivitySheet appears it appears in flipped state which is wrong.
This is the screenshot: 
<img width="487" alt="screen shot 2017-07-24 at 10 43 53 pm" src="https://user-images.githubusercontent.com/3787052/28537043-ff007a1e-70c2-11e7-8f0e-9d6c63636f20.png">

**Comment by jamesmontemagno** [comment]
You may wan to to just move it back. Not much I can do here. Unless you have ideas.
