### ISSUE TITLE
Body content overwrites subject content while sharing on gmail app in iOS on xamarin forms

### ISSUE THREAD

**Issue by atulinfy** [jguertl/SharePlugin#67]
[TestApp.zip](https://github.com/jguertl/SharePlugin/files/1189591/TestApp.zip)

**Comment by jamesmontemagno** [comment]
Please post a code sample and screen shots. Please don't upload a zip.

Closing and will let you create a new one.

**Comment by plarrea** [comment]
Same thing happening to me, nothing special in my code:

`CrossShare.Current.Share(new ShareMessage
{
                Title = "Subject",
                Text = "This is the body",
                Url = "some url"
});`

**Comment by jamesmontemagno** [comment]
Does this happen with Apple's Mail app?

**Comment by plarrea** [comment]
Not with native mail app only when selecting gmail app. I'd be happy with a UIActivityType to exclude it if fixing it is too complicated.

**Comment by jamesmontemagno** [comment]
I'm not doing anything special:

if (message.Text != null)
                    items.Add(new ShareActivityItemSource(new NSString(message.Text), message.Title));
                if (message.Url != null)
                    items.Add(new ShareActivityItemSource(NSUrl.FromString(message.Url), message.Title));

Most likely it is Gmails issue not the plugins.

**Comment by jamesmontemagno** [comment]
Lots of things here: https://stackoverflow.com/questions/29765806/uiactivityviewcontroller-gmail-share-subject-and-body-going-empty

Closing again since it works in standard app, which means we are following the rules.
