### ISSUE TITLE
Post to facebook not working

### ISSUE THREAD

**Issue by Srinivasdelta** [jguertl/SharePlugin#68]
Hi, 
I tried below code. Everything seems to work well to share except posting to facebook. I can able to share url but text not being copied to facebook post. 

var title = "title";
            var message = "message";

            if (!CrossShare.IsSupported)
                return;

         await CrossShare.Current.Share(new ShareMessage
            {
                Title = title,
                Text = message
         },
            new ShareOptions
            {
                ChooserTitle = "Share This To Your Friends"                
           
            });

**Comment by olecsiuyae** [comment]
I have the same issue

**Comment by proxymus89** [comment]
Same here

I'm on 5.0 version

**Comment by olecsiuyae** [comment]
Find out this - https://developers.facebook.com/bugs/332619626816423
So, it's not plugin issue

**Comment by proxymus89** [comment]
so this is an issue only for android platform?on IOS should be work?

**Comment by elsieyoung** [comment]
It will work on iOS if you add the following line in AppDelegate.cs

`Plugin.Share.ShareImplementation.ExcludedUIActivityTypes.Clear();`

This will remove Facebook from the ExcludedUIActivityTypes list.

**Comment by jamesmontemagno** [comment]
^ or pass in a blank list to the options.
