### ISSUE TITLE
Why the CrossCurrentActivity.Current.Activity hack (Activity isn't used)?

### ISSUE THREAD

**Issue by hardcodet** [jguertl/SharePlugin#69]
OpenBrowser unfortunately just opens and independent Chrome chrome instance (latest NuGet, XF 2.3.4.247, compiled against API level 25, phone is an S6 with API level 24). Works fine on iOS! Any hints on how I could diagnose this?

**Comment by hardcodet** [comment]
Ok, this seems to be because of that `if` condition here:

                if (CrossCurrentActivity.Current.Activity == null)
                {
                    var intent = new Intent(Intent.ActionView);
                    intent.SetData(Android.Net.Uri.Parse(url));

                    intent.SetFlags(ActivityFlags.ClearTop);
                    intent.SetFlags(ActivityFlags.NewTask);
                    Application.Context.StartActivity(intent);
               }

That activity is not set by the framework, but through a lot of callbacks in the sample's main activity. However, it's not used at all to actually launch the tabs. Why is this necessary in the first place?

**Comment by jamesmontemagno** [comment]
The current activity lays down a "MainApplication.cs" file into your application and it is required.

**Comment by jamesmontemagno** [comment]
It is used below: intent.LaunchUrl(CrossCurrentActivity.Current.Activity, Android.Net.Uri.Parse(url));

**Comment by hardcodet** [comment]
My bad about the usage. That's an embarassing one, sorry :/

About the MainApplication.cs - I don't have that file, and just setting the activity in the MainActivity as posted above works fine: My custom tabs are working now. You sure about that requirement?

**Comment by jamesmontemagno** [comment]
Yeah, it should add in: https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/files/MainApplication.cs.pp when you install the dependency. Not sure what mechanism you used to install the nuget though, but it should.
