### ISSUE TITLE
Facebook Post is "missing" on iOS

### ISSUE THREAD

**Issue by Goldstrike** [jguertl/SharePlugin#72]
Hello,

I've implemented the **SharePlugin** in my Xamarin.Forms project.

This works fine, but I meet a little "problem" on iOS: when I share a link,, I haven't the choice to post it on Facebook:
- [screenshot of my app - no Facebook](https://img11.hostingpics.net/pics/755194iOSAdpNoFacebook.jpg)

This option doesn't seem to be avalaible in the Activities list:
- [list of the activities - no Facebook](https://img11.hostingpics.net/pics/739354iOSAdpOptionsWithoutFacebook.jpg)

But on Android, there is no problem:
- [screenshot of my app - with Facebook](https://img11.hostingpics.net/pics/836513AndroidAdpFacebook.jpg)

However, if I use your sample, the "Facebook" option is well enabled on iOS:
- [from the app](https://img11.hostingpics.net/pics/267652iOSSampleFacebook.jpg)
- [in the list of activities](https://img11.hostingpics.net/pics/489765iOSSampleOptionsWithFacebook.jpg)

**_Would you have any explanation?_**

I've share the link like this:
```
private void OnShareIconClicked(object sender, EventArgs e)
{
    if (!CrossShare.IsSupported)
        return;

    CrossShare.Current.Share(new Plugin.Share.Abstractions.ShareMessage
    {
        Title = "MyApp",
        Text = _vm.AgendaEvent.encart_titre,
        Url = _vm.AgendaEvent.infos_url
    });
}
```

**Comment by Goldstrike** [comment]
After updating `Xamarin.Forms` package to `v2.4.0.269-pre2` and `Plugin.Share` to `v7.0.1` on your sample, I've seen that **Facebook** is not longer available.
Is it normal?

**Comment by jamesmontemagno** [comment]
https://github.com/jguertl/SharePlugin/issues/68
