### ISSUE TITLE
Can not make it work on UWP

### ISSUE THREAD

**Issue by 207713** [jguertl/SharePlugin#74]
CrossShare.IsSupported returns true, but, executing CrossShare.Current.OpenBrowser("https://www.google.com"); does literally nothing, not even a single crash!

Is there anything that has to be called in advance on UWP to use this plugin?

I'm sorry, i forgot to mention my problem is present **ONLY ON DESKTOP!**

**Comment by jamesmontemagno** [comment]
Call this code from your UWP app and see if there is an Exception:
```
 try
            {
                await Windows.System.Launcher.LaunchUriAsync(new Uri(url));

                return true;
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Unable to open browser: " + ex.Message);
                return false;
            }
```

**Comment by 207713** [comment]
This way it works, thank you very much, i'm just gonna call this via dependency service :)

**Comment by jamesmontemagno** [comment]
This is literally the code that the plugin uses... I copied and pasted it out and asked you to test it.

**Comment by 207713** [comment]
Well i'm just glad it works ^_^ Thanks again!
