### ISSUE TITLE
How to notice Share completed?

### ISSUE THREAD

**Issue by higher-faster-better** [jguertl/SharePlugin#76]
I am using this library in my Xamarin Forms project and it works good but there is no way to fire to share completed or cancelled.
Can you give me any solution?

Thanks.

**Comment by jamesmontemagno** [comment]
There is no good way to know this on any platform. It just tells you if it was triggered.

**Comment by higher-faster-better** [comment]
How about in Xamarin native? Does it have a good way to check it?

**Comment by jamesmontemagno** [comment]
Not that I am aware of.

**Comment by jamesmontemagno** [comment]
Even not in Xamarin, you just request the share.

**Comment by higher-faster-better** [comment]
In Native IOS, there is option for completion.

```
[activityViewController setCompletionWithItemsHandler:^(NSString *activityType, BOOL completed, NSArray *returnedItems, NSError *activityError) {
        if(completed){
           // blabla
        }       
    }];
```

In Native Android, there is also option for completion.

```
Intent share = new Intent(Intent.ACTION_SEND);
        share.setType("text/plain");
        share.putExtra(Intent.EXTRA_SUBJECT, "title");
        share.putExtra(Intent.EXTRA_TEXT,  "url");
        startActivityForResult(Intent.createChooser(share, "title", REQUEST_ACTION_SEND);
...

```
But it's not implemented in this package?

**Comment by jamesmontemagno** [comment]
No plans to implement this, you can fork and try to implement yourself or just grab the code from here.
