### ISSUE TITLE
Remove Dependency on Xamarin.Forms

### ISSUE THREAD

**Issue by jamesmontemagno** [jguertl/SharePlugin#8]
Hey there! So I have been in need of a share plugin and I didn't want to create one or re-invent the wheel here, but it seems as though you have abandoned this plugin. 

I have re-implemented Share for iOS, Android, and all Windows platforms without any dependencies for any app with or without Xamarin.Forms. 

https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Share

My proposal would be for me to come onto this project or for me to publish my own and you deprecate and remove this plugin. 

Let me know what you think. If by 10/30 I don't hear back I will publish my plugin.

**Comment by jguertl** [comment]
Hi James!

I would be glad to integrate the changes together with you. 
How would you like to proceed?

**Comment by jamesmontemagno** [comment]
Hey there!

Awesome, so instead of me releasing a new package I would like to do a few
things. Add some new APIs, upgrade to unified, add more platforms.

Since we will drop the Xamarin.Forms dependency and also I propose a name
change to the package, namespace, and call it a 2.0.0 with breaking
changes.

This would further future proof it and would allow more developers to use
the package.

If you could add me as a contributor to your repo and also add me to the
nuget package I will create a 2.0.0 branch to work out of.

How does that sound?

James

**Comment by jguertl** [comment]
Yeah, that sounds good. I just added you as a contributor to to repo and the NuGet package.

**Comment by jamesmontemagno** [comment]
Lovely! Starting today.
