### ISSUE TITLE
Latest version of Xamarin Forms Prevents Install

### ISSUE THREAD

**Issue by dberroa** [jguertl/SharePlugin#80]
I started a project a few days ago and tried to install this plugin. I have Xamarin Forms v2.5.0.121934 with the Xamarin Support libraries at version 25.4.0.2. I get the following error:

Install-Package : Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 Test.Android -> Xamarin.Android.Support.v7.MediaRouter 25.4.0.2 -> Xamarin.Android.Support.v7.Palette 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2) 
 
Test.Android -> Plugin.Share 7.0.1 -> Xamarin.Android.Support.CustomTabs 25.3.1 -> Xamarin.Android.Support.Compat (= 25.3.1).

I believe this plugin needs to be updated to support the latest Xamarin forms or I'm missing something on downgrading the android libraries. It doesn't seem to let me due to Xamarin forms dependencies.

**Comment by jamesmontemagno** [comment]
Works just fine, maybe install chrome custom tabs version 25.4.0.2 manually first. 

Se dependencies here: https://www.nuget.org/packages/Plugin.Share/7.0.1

**Comment by dberroa** [comment]
Adding that manually fixed it. Thank you. Sorry for the mistake.
