### ISSUE TITLE
The "GenerateJavaStubs" task failed unexpectedly

### ISSUE THREAD

**Issue by nqbjnh** [jguertl/SharePlugin#83]
Hi, 
I Used SharePlugin for xamarin forms, IOS good working, but android i get a error The "GenerateJavaStubs" task failed unexpectedly when build project.
How to resolve it?
Thank

**Comment by prashantvc** [comment]
Could you share the [full build output](https://developer.xamarin.com/guides/cross-platform/troubleshooting/questions/version-logs/#verbose-build-output-logs)? It will help us to troubleshoot the issue
