### ISSUE TITLE
Button color does not respect main style

### ISSUE THREAD

**Issue by maquiavelli** [jguertl/SharePlugin#85]
When I use ShareMessage it does not use the default bar settings and uses the system default.

![a](https://user-images.githubusercontent.com/5720620/35919183-7467b654-0bfb-11e8-9ffe-ea83e6a37016.png)

**Comment by jamesmontemagno** [comment]
Did you set the UIAppearanc in your AppDelegate? https://stackoverflow.com/questions/25795065/ios-8-uiactivityviewcontroller-and-uialertcontroller-button-text-color-uses-wind
