### ISSUE TITLE
[Question] PostToFacebook disabled by default

### ISSUE THREAD

**Issue by AndreiMisiukevich** [jguertl/SharePlugin#86]
Hi, thanks for your work.

I have a question.

`public static List<NSString> ExcludedUIActivityTypes { get; set; } = new List<NSString> { UIActivityType.PostToFacebook };`

Why is PostToFacebook disabled by default? It's strange a little) I spent some time to understand, why there is ability to post to facebook on iPhone)

Thanks

**Comment by jamesmontemagno** [comment]
Because it doesn't work at all. Facebook remove the capability if you post to facebook then it opens a blank dialog.
