### ISSUE TITLE
Save files 

### ISSUE THREAD

**Issue by CarLoOSX** [jguertl/SharePlugin#88]
Hello everyone, I guess I'm not the only one who has tried to find this option:

I would like to know if it is possible. Thank you!

![img_1270](https://user-images.githubusercontent.com/9008334/36588008-19ef4ef6-1887-11e8-9eda-3d5c7b4ed70f.png)

**Comment by jamesmontemagno** [comment]
No new functionality will be added to this library and all are moving to https://github.com/xamarin/Essentials
