### ISSUE TITLE
Please support Android 26

### ISSUE THREAD

**Issue by JaeWLee** [jguertl/SharePlugin#89]
Maybe now, this project not support Android 26 >=

Please support...

Thanks james and jguertl 
I am using this project well because of you guys.

**Comment by JaeWLee** [comment]
Plugin.Share 7.1.1 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

**Comment by jamesmontemagno** [comment]
already supports it, you just need to install the proper nugets
