### ISSUE TITLE
OpenBrowser opens Chrome instead of CustomTab

### ISSUE THREAD

**Issue by AnatolyUA** [jguertl/SharePlugin#90]
When I invoke CrossShare.Current.OpenBrowser(url, options); in Android app it starts system browser. In code I use CrossShare.IsSupported and its value is true, but CrossShare.Current.OpenBrowser does the same as Device.OpenUri. What can be wrong? CrossShare.Current.OpenBrowser works correct on iOS in the same solution. 

![screenshot_2018-03-06-15-04-28](https://user-images.githubusercontent.com/1446703/37036051-2bd34db0-2157-11e8-8085-2d1136178703.png)

Here is NuGet packages list:
`<ItemGroup>

    <PackageReference Include="CarouselView.FormsPlugin">
      <Version>5.2.0</Version>
    </PackageReference>
    <PackageReference Include="DLToolkit.Forms.Controls.FlowListView">
      <Version>2.0.10</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Distribute">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Push">
      <Version>1.5.0</Version>
    </PackageReference>
    <PackageReference Include="Plugin.Share">
      <Version>7.1.1</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.5.166-beta</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.CustomTabs">
      <Version>26.1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading">
      <Version>2.3.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.3.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.280555" />
    <PackageReference Include="Xamarin.Android.Support.Design" Version="26.1.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="26.1.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="26.1.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="26.1.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="26.1.0.1" />
  </ItemGroup>`

**Comment by jamesmontemagno** [comment]
Seems to work for me. When you actually select chrome what does it look like?

**Comment by AnatolyUA** [comment]
It opens Chrome. 
I have tested it on devices (Android 5.0 / API 21 & Android 5.1 / API 22). 
Here is the solution: [CrossShareTest.zip](https://github.com/jguertl/SharePlugin/files/1786492/CrossShareTest.zip)

**Comment by AnatolyUA** [comment]
same story with Android 7 / API 24

**Comment by jamesmontemagno** [comment]
Unable to reproduce on my Pixel 2, Emulators, Nexus 6, or S8

**Comment by 15mgm15** [comment]
@jamesmontemagno I can reproduce this with Samsung Galaxy S7 with Android 7.0. Is this still a thing? are ChromeCustomTabs going to be deprecated?
