### ISSUE TITLE
NuGet error when upgrading Xamarin.Android.Support.Compat packages

### ISSUE THREAD

**Issue by vividos** [jguertl/SharePlugin#91]
I have a Xamarin.Forms project that references the Xamarin.Android.Support-NuGet packages, currently version 25.4.0.2. The project also references your SharePlugin, version 7.1.1. When I try to upgrade the Android Support packages, I get this error:

```
NU1107: Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 WhereToFly.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2 -> Xamarin.Android.Support.v7.Palette 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
 WhereToFly.Android -> WhereToFly.Core -> WhereToFly.Logic -> Plugin.Share 7.1.1 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).
```

The reason for this is, that the Share plugin version 7.1.1 still uses Xamarin.Android.Support.CustomTabs 25.4.0.2. Could you upgrade those packages and issue a new NuGet package of the SharePlugin? That would help me upgrading all NuGet packages. Many thanks!
Michael

**Comment by StreetMaster** [comment]
I have the same problem

**Comment by jamesmontemagno** [comment]
Add the latest version of custom and first.

**Comment by jamesmontemagno** [comment]
Add latest version of custom tabs and then upgrade others. This is a nuget issue

**Comment by vividos** [comment]
Thanks, that fixed the problem! I added the latest version of Xamarin.Android.Support.CustomTabs to my Xamarin.Forms project after updating the other Xamarin.Android.Support packages, and then it worked.

**Comment by dpedrinha** [comment]
Didn't work for me.
I had to first install xamarin.android.support.annotations, then ***.compat, then ***.CustomTabs, then ***.Core.UI, then ***.Core.Utils, then ***.Fragment, then ***.Media.Compat
And only then I was able to install the updates available.

**Comment by vividos** [comment]
Well, in the end it also didn't work for me. I had to downgrade to Xamarin.Android.Support libraries 25.4.0.2 in order to use the SharePlugin.

**Comment by vividos** [comment]
For anyone interested in the solution, here's the commit in my github project:
https://github.com/vividos/WhereToFly/commit/5c800f321653bcc9415e38202b4d7d0505f179a7
I had to update the Xamarin.Android.Support.* projects to 27.0.2. Then I got the error in my first comment, and to fix this I had to manually add the Xamarin.Android.Support.CustomTabs to my Android project, even though I don't use it. Rebuilding, and the NuGet error went away.

**Comment by upskydownshoes** [comment]
Good job I have time on my hands and there are people like @dpedrinha around because I would have given up on Xamarin a long time ago. 2 days in and I'm still working on getting the Xamarin HelloWorld example to work. Sheeesh. Thanks @dpedrinha

**Comment by upskydownshoes** [comment]
Having said that @dpedrinha, if you have a minute to point to how you knew to: 

"first install xamarin.android.support.annotations, then ***.compat, then ***.CustomTabs, then ***.Core.UI, then ***.Core.Utils, then ***.Fragment, then ***.Media.Compat"

That would be fab ... in the spirit of "teach a man to fish" n all :-)

**Comment by KalpeshChheda** [comment]
Hi @upskydownshoes 

> "first install xamarin.android.support.annotations, then ***.compat, then ***.CustomTabs, then ***.Core.UI, then ***.Core.Utils, then ***.Fragment, then ***.Media.Compat"

Its working. Thanks.

**Comment by dpedrinha** [comment]
It's been a long time mate, I don't remember in detail. All I remember is that I tried installing the package I needed and saw an error regarding ***.Media.Compat. Tried installing ***.Media.Compat and got another error regarding ***.Fragment. Tried ***.Fragment and got error about ***.Core.Utils.......... And so on. I kept trying the packages with errors until one worked and now I knew exactly the ones I needed and the right order.

**Comment by upskydownshoes** [comment]
Fantastic cheers, reproduced it and found the error refs. You're a star. I tell you, for a newbie, Visual Studio is a minefield. Thanks again for response!

**Comment by fm698** [comment]
I still having the problem,
When adding the latest version of Xamarin.Android.Support.CustomTabs  , it gives me error that its not compatible with .netstandard 2 ?

**Comment by mr5z** [comment]
I have managed to update all the packages: Xamarin.Android.* by adding the 27.0.2.1 versions of packages below and then update them one by one in trial and error order to 28.0.0

> Xamarin.Android.Support.Design 28.0.0
> Xamarin.Android.Support.v7.AppCompat 28.0.0
> Xamarin.Android.Support.v4 28.0.0
> Xamarin.Android.Support.v7.CardView 28.0.0
> Xamarin.Android.Support.v7.MediaRouter 28.0.0
> Xamarin.Android.Support.CustomTabs 28.0.0
> Xamarin.Android.Support.Core.Utils 28.0.0
> Xamarin.Android.Support.Compat 28.0.0
> Xamarin.Android.Support.Annotations 28.0.0
> Xamarin.Android.Support.Core.UI 28.0.0
> Xamarin.Android.Support.v7.RecyclerView 28.0.0
> Xamarin.Android.Support.Media.Compat 28.0.0
> Xamarin.Android.Support.Fragment 28.0.0

Upon installing this, take note that you need to enable Multidexing in your Android project (which sucks)

**Comment by cizu64** [comment]
Just edit the csproj file and add this manually:

 <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.0.0.135214-pre4" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Compat" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Core.UI" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Fragment" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Media.Compat" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Annotations" Version="27.0.2.1" />
  </ItemGroup>

**Comment by cizu64** [comment]
Just edit the csproj file and add this:

```
 <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.0.0.135214-pre4" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Compat" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Core.UI" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Fragment" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Media.Compat" Version="27.0.2.1" />
    <PackageReference Include="Xamarin.Android.Support.Annotations" Version="27.0.2.1" />
  </ItemGroup>
```

**Comment by jzuma75** [comment]
> It's been a long time mate, I don't remember in detail. All I remember is that I tried installing the package I needed and saw an error regarding ***.Media.Compat. Tried installing ***.Media.Compat and got another error regarding ***.Fragment. Tried ***.Fragment and got error about ***.Core.Utils.......... And so on. I kept trying the packages with errors until one worked and now I knew exactly the ones I needed and the right order.

This worked for me, except I had to downgrade every Support package to 27.0.2.1 first

**Comment by danielkon96** [comment]
> Just edit the csproj file and add this:
> 
> ```
>  <ItemGroup>
>     <PackageReference Include="Xamarin.Forms" Version="4.0.0.135214-pre4" />
>     <PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Compat" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Core.UI" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Fragment" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Media.Compat" Version="27.0.2.1" />
>     <PackageReference Include="Xamarin.Android.Support.Annotations" Version="27.0.2.1" />
>   </ItemGroup>
> ```

Thank you SO MUCH! This worked flawlessly and should be posted elsewhere because it was very difficult to find. If you are having issues updating, go to this and change 27.0.2.1 to the version you are trying to update to.
