### ISSUE TITLE
Sharing a URL with a space in it, causes sharing to fail

### ISSUE THREAD

**Issue by dpcouch** [jguertl/SharePlugin#93]
When you try and share a url with a space in the name, the plugin fails to share the link.

Current work around is to urlencode the url.

**Comment by jamesmontemagno** [comment]
Have you tried to use Xamarin.Essentials. That is the next evolution: https://docs.microsoft.com/en-us/xamarin/essentials/data-transfer?context=xamarin%2Fxamarin-forms&tabs=ios
