### ISSUE TITLE
How would I known which Option is selected event?

### ISSUE THREAD

**Issue by jitendrajadav** [jguertl/SharePlugin#96]
How would I known which Option is selected event?

**Comment by jamesmontemagno** [comment]
Need more information as to what you are doing.

**Comment by jitendrajadav** [comment]
Please find below image I have circle particular Option so that I wanted to know I have to send Message accordingly I can code something.

so my question is how I can get event handler for any selected Item?

![shareimage](https://user-images.githubusercontent.com/1029026/40417048-79ce5154-5e9c-11e8-8771-9d5aaf40747c.jpg)

**Comment by jamesmontemagno** [comment]
There is know way to know what the user selected as the APIs don't exist to do this.

**Comment by jitendrajadav** [comment]
@jamesmontemagno I am not sure about iOS how is handling in our current project we have capability to select particular option and perform how iOS handled?
