### ISSUE TITLE
SDK android 8.0

### ISSUE THREAD

**Issue by coin90** [jguertl/SharePlugin#97]
Exception Target not support in sdk android 8.0

**Comment by coin90** [comment]
With a little help I would love to be able to contribute to the nugget and be able to resolve the Issue

**Comment by jamesmontemagno** [comment]
Should work just fine, what/where are you seeing this?

**Comment by coin90** [comment]
when using CrossShare.Current.Share gives this exception:

[Error] Error-This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.|class=ShareApp|method=ShareAppBySocialNetworkTapped|errorMessage=This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.  

The target framework is 8.0 and I have the last version de Xamarin.Android.Support.CustomTabs.
In iOs work done.

**Comment by coin90** [comment]
In the end the error was mine, I have several android projects in the same solution, and in some I was missing the reference to the project. Thank you very much for the help and for what you contribute to the community
